//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSite_ShowRoom_CtyThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NhanVien
    {
        public string MSNV { get; set; }
        public string SDT { get; set; }
        public string TenNhanVien { get; set; }
        public string CCCD { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Image { get; set; }
        public System.DateTime Birthday { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
        public decimal Lương { get; set; }
        public string GioiTinh { get; set; }
        public string Role { get; set; }
    }
}
